# Generated by Django 2.2.16 on 2021-08-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'комментарии', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'подписки', 'verbose_name_plural': 'подписки'},
        ),
    ]
