# Generated by Django 2.2.16 on 2021-08-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210831_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'комментарии', 'verbose_name_plural': 'комментарии'},
        ),
    ]
